# Generated by Django 4.0.2 on 2022-08-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CUTOVER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FIORI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('already_mapped', models.CharField(blank=True, max_length=100, null=True, verbose_name='Already Mapped')),
                ('master_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Master Name')),
                ('section', models.CharField(blank=True, max_length=100, null=True, verbose_name='Section')),
                ('name_of_field', models.CharField(blank=True, max_length=100, null=True, verbose_name='Field Name')),
                ('group_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Group 1')),
                ('group_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Group 2')),
                ('group_3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Group 3')),
                ('type_of_field', models.CharField(blank=True, max_length=100, null=True, verbose_name='Field Type')),
                ('data_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Data Type')),
                ('sbu', models.CharField(blank=True, max_length=100, null=True, verbose_name='SBU')),
                ('customer_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Customer Type')),
                ('applicability', models.CharField(blank=True, max_length=100, null=True, verbose_name='Applicability')),
                ('possible_sources', models.CharField(blank=True, max_length=100, null=True, verbose_name='Possible Sources')),
                ('remarks', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remarks')),
                ('purpose', models.CharField(blank=True, max_length=100, null=True, verbose_name='Purpose')),
                ('legacy_field', models.CharField(blank=True, max_length=100, null=True, verbose_name='Legacy Field')),
                ('comments', models.CharField(blank=True, max_length=100, null=True, verbose_name='Comments')),
                ('mdg_rules_1', models.CharField(blank=True, max_length=1000, null=True, verbose_name='MDG Rule 1')),
                ('mdg_rules_2', models.CharField(blank=True, max_length=1000, null=True, verbose_name='MDG Rule 2')),
                ('mdg_rules_3', models.CharField(blank=True, max_length=1000, null=True, verbose_name='MDG Rule 3')),
                ('mdg_rules_4', models.CharField(blank=True, max_length=1000, null=True, verbose_name='MDG Rule 4')),
                ('mdg_rules_5', models.CharField(blank=True, max_length=1000, null=True, verbose_name='MDG Rule 5')),
                ('action', models.CharField(blank=True, max_length=100, null=True, verbose_name='Action')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Created By')),
                ('create_on', models.DateField(null=True, verbose_name='Created On')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Updated By')),
                ('updated_on', models.DateField(null=True, verbose_name='Updated On')),
            ],
        ),
        migrations.CreateModel(
            name='PERIPHERALS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
