# Generated by Django 4.0.2 on 2022-08-03 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kds',
            options={'verbose_name': 'KDS', 'verbose_name_plural': 'KDS`s'},
        ),
    ]
