# Generated by Django 4.0.2 on 2022-08-03 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_dashboard', '0002_alter_kds_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kds',
            old_name='create_on',
            new_name='created_on',
        ),
    ]
