# Generated by Django 4.0.2 on 2022-08-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_dashboard', '0006_alter_kds_created_on_alter_kds_updated_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='UNITTEST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_test', models.CharField(blank=True, max_length=1000, verbose_name='Data')),
                ('data', models.CharField(blank=True, max_length=1000, verbose_name='Data')),
                ('value_code', models.CharField(blank=True, max_length=1000, verbose_name='Value/Code')),
                ('desc_ut', models.CharField(blank=True, max_length=1000, verbose_name='Description')),
                ('comments_ut', models.CharField(blank=True, max_length=1000, verbose_name='Comments')),
                ('screenshot', models.FileField(blank=True, upload_to='', verbose_name='Screenshot of Error')),
                ('created_by_ut', models.CharField(blank=True, max_length=100, null=True, verbose_name='Created By')),
                ('created_on_ut', models.DateField(blank=True, null=True, verbose_name='Created On')),
                ('updated_by_ut', models.CharField(blank=True, max_length=100, null=True, verbose_name='Updated By')),
                ('updated_on_ut', models.DateField(blank=True, null=True, verbose_name='Updated On')),
            ],
        ),
        migrations.RemoveField(
            model_name='fiori',
            name='test',
        ),
    ]
