# Generated by Django 4.0.2 on 2022-08-04 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_dashboard', '0007_unittest_remove_fiori_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unittest',
            options={'verbose_name': 'Unit Test', 'verbose_name_plural': 'Unit Tests'},
        ),
    ]
