# Generated by Django 4.0.2 on 2022-08-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_dashboard', '0009_unittest_done_flag_unittest_value_entered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kds',
            name='link',
            field=models.CharField(default='Edit', max_length=100),
        ),
    ]
