# Generated by Django 4.0.2 on 2022-08-05 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_dashboard', '0010_kds_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='UTMASTER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_case_id', models.CharField(max_length=100, unique=True, verbose_name='Test Case ID')),
                ('test_case_name', models.CharField(max_length=100, unique=True, verbose_name='Test Case Name')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('business_process', models.CharField(max_length=500, verbose_name='Business Process')),
                ('pre_requisites', models.CharField(max_length=500, verbose_name='Prerequisites')),
                ('business_process_owner', models.CharField(max_length=500, verbose_name='Business Process Owner')),
                ('test_owner_acc', models.CharField(max_length=300, verbose_name='Test Owner Acc.')),
                ('test_cycle', models.CharField(max_length=300, verbose_name='Test Cycle')),
                ('sap_sys_client', models.CharField(max_length=500, verbose_name='SAP System & Client')),
                ('execution_date', models.CharField(max_length=300, verbose_name='Execution Date')),
                ('process_desc', models.CharField(max_length=300, verbose_name='Process Description')),
            ],
        ),
        migrations.RenameField(
            model_name='unittest',
            old_name='created_by_ut',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='unittest',
            old_name='created_on_ut',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='unittest',
            old_name='updated_by_ut',
            new_name='updated_by',
        ),
        migrations.RenameField(
            model_name='unittest',
            old_name='updated_on_ut',
            new_name='updated_on',
        ),
        migrations.RemoveField(
            model_name='unittest',
            name='comments_ut',
        ),
        migrations.RemoveField(
            model_name='unittest',
            name='data',
        ),
        migrations.RemoveField(
            model_name='unittest',
            name='desc_ut',
        ),
        migrations.RemoveField(
            model_name='unittest',
            name='done_flag',
        ),
        migrations.RemoveField(
            model_name='unittest',
            name='screenshot',
        ),
        migrations.RemoveField(
            model_name='unittest',
            name='unit_test',
        ),
        migrations.RemoveField(
            model_name='unittest',
            name='value_code',
        ),
        migrations.RemoveField(
            model_name='unittest',
            name='value_entered',
        ),
        migrations.AddField(
            model_name='unittest',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Test Completed'),
        ),
        migrations.AddField(
            model_name='unittest',
            name='mark_for_deletion',
            field=models.BooleanField(default=False, verbose_name='Mark For Deletion'),
        ),
        migrations.AddField(
            model_name='unittest',
            name='remarks',
            field=models.TextField(null=True, verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='unittest',
            name='test_case_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_case_id_set', to='activity_dashboard.utmaster', to_field='test_case_id'),
        ),
        migrations.AddField(
            model_name='unittest',
            name='test_case_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_case_name_set', to='activity_dashboard.utmaster', to_field='test_case_name'),
        ),
    ]
