# Generated by Django 4.0.2 on 2022-08-05 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_dashboard', '0011_utmaster_rename_created_by_ut_unittest_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unittest',
            old_name='test_case_name',
            new_name='test_case',
        ),
        migrations.RemoveField(
            model_name='unittest',
            name='test_case_id',
        ),
    ]
