# Generated by Django 4.0.2 on 2022-08-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_dashboard', '0012_rename_test_case_name_unittest_test_case_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unittest',
            name='attachment',
            field=models.FileField(blank=True, upload_to='uploads/', verbose_name='Attachments'),
        ),
    ]
