# Generated by Django 4.0.2 on 2022-08-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_dashboard', '0015_remove_unittest_image_unittest_error_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utmaster',
            name='execution_date',
            field=models.DateField(null=True, verbose_name='Execution Date'),
        ),
    ]
